baseURL = 'http://gym-scores.github.io'
languageCode = 'en-us'
title = 'gym-scores'

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

sectionPagesMenu = 'main'

    [params.flexsearch] # Parameters for FlexSearch
        enabled             = true

    [params.docs] # Parameters for the /docs 'template'
         title           = "The Scores"           # default html title for documentation pages/sections

        # pathName        = "docs"                            # path name for documentation site | default "docs"

        # themeColor      = "cyan"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = true                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        prismTheme      = "solarized-light"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true